flags: {}
extra-package-dbs: []
local-bin-path: ./bin
packages:
- '.'
- deps/compact-indexed/
system-ghc: true
docker:
  auto-pull: true
  repo: vikraman/ghc-mutable-cnf:0.3
extra-deps:
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.0
- atomic-primops-0.8.0.3
- clock-0.6.0.1
- mtl-2.2.1
- optparse-applicative-0.12.1.0
- parsec-3.1.9
- primitive-0.6.1.0
- regex-base-0.93.2
- regex-tdfa-rc-1.1.8.3
- stm-2.4.4.1
- tagged-0.8.3
- tasty-0.11.0.2
- tasty-hunit-0.9.2
- text-1.2.2.1
- transformers-compat-0.5.1.4
- unbounded-delays-0.1.0.9
- vector-0.11.0.0
compiler-check: newer-minor
resolver: ghc-7.11
