flags: {}
extra-package-dbs: []
local-bin-path: ./bin
packages:
- '.'
- deps/compact-indexed/
system-ghc: true
docker:
  auto-pull: true
  repo: vikraman/ghc-mutable-cnf:0.2
extra-deps:
- Glob-0.7.5
- abstract-deque-0.3
- abstract-par-0.3.3
- aeson-0.11.1.4
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.0
- atomic-primops-0.8.0.3
- attoparsec-0.13.0.1
- blaze-builder-0.4.0.1
- cassava-0.4.5.0
- cereal-0.5.1.0
- clock-0.6.0.1
- criterion-1.1.1.0
- dlist-0.7.1.2
- erf-2.0.0.0
- fail-4.9.0.0
- hashable-1.2.4.0
- hastache-0.6.1
- ieee754-0.7.8
- math-functions-0.1.5.2
- monad-par-0.3.4.7
- monad-par-extras-0.3.3
- mtl-2.2.1
- mwc-random-0.13.4.0
- optparse-applicative-0.12.1.0
- parallel-3.2.1.0
- parsec-3.1.9
- primitive-0.6.1.0
- random-1.1
- regex-base-0.93.2
- regex-tdfa-rc-1.1.8.3
- scientific-0.3.4.6
- semigroups-0.18.1
- statistics-0.13.2.3
- stm-2.4.4.1
- syb-0.6
- tagged-0.8.3
- tasty-0.11.0.2
- tasty-hunit-0.9.2
- text-1.2.2.1
- transformers-compat-0.5.1.4
- unbounded-delays-0.1.0.9
- unordered-containers-0.2.7.0
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- vector-binary-instances-0.2.3.1
- vector-th-unbox-0.2.1.4
compiler-check: newer-minor
resolver: ghc-7.11
